### ISSUE TITLE
Sync based on video frames

### ISSUE THREAD

**Issue by drolex2** [rpuntaie/syncstart#10]
I want to determine the offset between two video tracks. Do you think it would be fairly easy to add the ability to do the cross correlation on video?

I imagine that you might need the video or frames in a standard, raw format, and it could help to resize both video clips to a small size. The following ffmpeg command would resize the video to a height of 150 (retaining aspect ratio) and then crop about the center to 4:3 aspect ratio, which might be especially helpful when trying to compare two videos with different aspect ratios.

ffmpegrawvideo = 'ffmpeg -i "{}" -t %s -vf "scale=-1:150,crop=200:150" -c:v rawvideo -pix_fmt yuv420p -map 0:v "{}"'

Am I on the right track? Would you want to add the rest of what would be needed or guide me a bit?

**Comment by drolex2** [comment]
I see that someone was able to do this. He explained what he did, but didn't share any code.
[https://dsp.stackexchange.com/questions/18846/map-time-difference-between-two-similar-videos?newreg=71685ccb35a84880b96ec7d4f89ed233](https://dsp.stackexchange.com/questions/18846/map-time-difference-between-two-similar-videos?newreg=71685ccb35a84880b96ec7d4f89ed233)

**Comment by rpuntaie** [comment]
I had a look at the link:

- make two linear signal, eg using average brightness
- normalize the signals the way explained in your link
- then apply `corrabs` of syncstart.py

syncstart.py could have an option to select video instead of audio

**Comment by drolex2** [comment]
Feature added in #11
