### ISSUE TITLE
[Feature request]: Perform sync automatically

### ISSUE THREAD

**Issue by roaldarbol** [rpuntaie/syncstart#3]
Great work on this tool! Would you consider implementing the actual `ffmpeg` sync in there too? 
E.g. sync start and trim any lagging part of the videos too, and output new videos with `_synced` appended to the name. 
There's [ffmpy](https://ffmpy.readthedocs.io/en/latest/index.html) for using `ffmpeg` in python which could be good for writing a function.
If you don't have time to look at it I can see if I can put together a pull request if I can figure it out. Alternatively, can `syncstart` be used within Python, and in that case what would a minimal example of that look like?
Thanks!

**Comment by rpuntaie** [comment]
It can be done within Python. I just happened to use a shell script.

I wanted to do it over the week-end, but didn't find time.
I was thinking of keeping everything backward compatible,
and just add an option for this feature.
A pull request is very welcome.

For a usage of `syncstart.file_offset` see `test_syncstart.py`.

**Comment by roaldarbol** [comment]
Sounds great to include it as another option. I'm gone for a while, but will try to take a look at it in a month's time. :-)

**Comment by IchBinGROOT** [comment]
Any news on this? I was about to write a script for exactly this before I found this project.

**Comment by rpuntaie** [comment]
It should do to make your own local bash script that uses `syncstart.py` for local situations where it has proven to be reliable. No plan to do anything in `syncstart.py` itself.
