### ISSUE TITLE
Feature requests and memory usage

### ISSUE THREAD

**Issue by skinkie** [rpuntaie/syncstart#4]
First of all; my compliments. This has been the first package that works on recent python installations and but the results were not accurate. My usecase is the following. I have a input files from a Rode Wireless Go II backup recording. Lets call it 'the backup master track' it is about 30 minutes of audio.

In my ideal world I would be able to input N segments of input recordings (for example from a microphone camera) and get the synchronisation of the segment with respect to the backup master track.

So far, I have see that syncstart is memory hungry, maybe that could be reduced by some pragmatic effort, like lowering the samplerate, to find candidate positions, and for better allignment do it on the full amount. Obivously the ultimate result would be an edit decision list, with all segments aligned.

One out of five segments came out correctly, for this to work I needed to increase the "-t" option to 1800.

**Comment by rpuntaie** [comment]
syncstart only syncs the beginning of two files.

For your scenario one would need to cut the long 30 minute video into N segments at rounded times and apply syncstart 1-to-1, 2-to-2, ..., n-to-n. I would make a shell script for this.

**Comment by skinkie** [comment]
I have used https://github.com/alopatindev/sync-audio-tracks which basically can handle the trick. But I think having the ability to index the master track, and then be able to apply subparts to that, would be useful.
