### ISSUE TITLE
Parameter for starting position

### ISSUE THREAD

**Issue by IchBinGROOT** [rpuntaie/syncstart#6]
[Feature Request]

I have a lot of pairs of TV recordings in English and synchronized German. Of course in both containers there are a video and an audio stream. 
As I record the movies/shows from TV, I take into account that they are not on point, so I start 20 seconds or so early, so that I don’t miss the beginning. Now, in order to sync the two recordings, I need to sync on some distinctive sound, e.g. the intro soundtrack. 
Usually, the interesting parts of both files start about the same time into the video, so I would only need to specify one starting points. Would it be possible to include this in the library?

**Comment by rpuntaie** [comment]
Let X and Y be the two recordings. Let Z be the sound/intro you look for. Sync X with Z and Y with Z. You get XZ and YZ, the cut times from X and Y, both with respect to Z. You can now cut XZ from X and YZ from Y to bring X and Y in sync with each other and with Z. Or you can cut (XZ-XZ) from X if positive or Y if negative.

**Comment by IchBinGROOT** [comment]
Maybe my description was not clear, or I misunderstand your answer: the aforementioned intro is part of each of the two files. I think it would be the perfect point to start the syncing algorithm. It just happens not to be at the beginning of the video files.

**Comment by rpuntaie** [comment]
syncstart syncs the start of two files comparing the starting wave. It might work with just the two files. If it does not work, a third file could help, because you can put in there a specific wave you are looking for.  That is what I meant.
