### ISSUE TITLE
Support multi-audio files

### ISSUE THREAD

**Issue by NePoCz** [rpuntaie/syncstart#7]
Thanks for this great and easy to use tool,  does what it should, but found one problem. Currently, if one of the files contains more than one audio track, the program will error-out: 

`[wav @ 0x55c72c8260] WAVE files have exactly one stream`
`Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 --`

Workaround is to hardcode the first audio stream into the ffmpeg command inside your script, but that is far from ideal - but I guess still better than an error. Of course there is always the option to first extract the right tracks manually, in separate step. But I think an option to specify the audio track (for each file) should not be a huge problem. Unfortunatelly I have very little experience with python, so don't fancy a PR

**Comment by drolex2** [comment]
Multiple audio channels are merged into a mono track as of now with #11.

**Comment by rpuntaie** [comment]
A backward compatible proposal of change would have been needed here.
