### ISSUE TITLE
Help adding a command option

### ISSUE THREAD

**Issue by drolex2** [rpuntaie/syncstart#9]
Hello and thank you for this project. I've forked it and I'm trying to add a command option [-b BEGIN, --begin BEGIN]. This option uses the ffmpeg option -ss to begin the comparison X seconds into the inputs. I should be very close, but there is small error. Would you please guide me on completing this?

The error I get is:
syncstart.py", line 71, in normalize_denoise
    in_out(ffmpegwav%take,infile,outfile)
TypeError: not enough arguments for format string

I previously tried making that as follows, but it did not work. I'm not sure where %take comes from.
`in_out(ffmpegwav%begin%take,infile,outfile)`

Here is my forked version:: [https://github.com/drolex2/syncstart/blob/main/syncstart.py](https://github.com/drolex2/syncstart/blob/main/syncstart.py)

**Comment by rpuntaie** [comment]
Since you have added another `%s` to `ffmpegwav`,
you should do `ffmpegwav%(begin,take)` instead of just `ffmpegwav%take`.

**Comment by drolex2** [comment]
Thanks! It's working.
